name: Enforce Team-Based Approvals

on:
  pull_request:
    branches:
      - develop  # Apply this workflow only to PRs merging into develop
    types: [submitted]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Approvals
        id: approvals
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR Number: $PR_NUMBER"

          REVIEWS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     "https://api.github.com/repos/hdfcorg/hdfc/pulls/$PR_NUMBER/reviews")
          echo "$REVIEWS" > reviews.json
          echo "Fetched PR Reviews Successfully."

      - name: Debug PR Approvals
        run: cat reviews.json  # Log review details for debugging

      - name: Validate Approvers from Different Teams
        id: validate_teams
        run: |
          ORGANIZATION="hdfcorg"
          TEAM_A="teamahdfc"
          TEAM_B="teambsidgs"

          TEAM_A_APPROVED=0
          TEAM_B_APPROVED=0

          # Fetch team members
          TEAM_A_MEMBERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                  -H "Accept: application/vnd.github.v3+json" \
                                  "https://api.github.com/orgs/$ORGANIZATION/teams/$TEAM_A/members" | jq -r '.[].login')

          TEAM_B_MEMBERS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                  -H "Accept: application/vnd.github.v3+json" \
                                  "https://api.github.com/orgs/$ORGANIZATION/teams/$TEAM_B/members" | jq -r '.[].login')

          echo "Team A Members: $TEAM_A_MEMBERS"
          echo "Team B Members: $TEAM_B_MEMBERS"

          # Extracting approved users from PR
          for USER in $(jq -r '.[] | select(.state=="APPROVED") | .user.login' reviews.json); do
            echo "Checking approval from: $USER"

            # Check if user is in TEAM_A
            if echo "$TEAM_A_MEMBERS" | grep -qw "$USER"; then
              TEAM_A_APPROVED=1
              echo "$USER is in Team A"
            fi

            # Check if user is in TEAM_B
            if echo "$TEAM_B_MEMBERS" | grep -qw "$USER"; then
              TEAM_B_APPROVED=1
              echo "$USER is in Team B"
            fi
          done

          # Ensure at least one approval from each team
          if [[ $TEAM_A_APPROVED -eq 0 || $TEAM_B_APPROVED -eq 0 ]]; then
            echo "❌ Error: One approval from each team is required!"
            exit 1
          else
            echo "✅ Approvals from both teams are verified."
          fi

      - name: Block Merge if Conditions Fail
        if: failure()
        run: |
          echo "❌ Merge is blocked. Approvals from both teams are required."
          exit 1
